#  Manifest do create configuration of Deployment from a docker image in a kubernet cluster.
#  Using only the Deployment kubectl automatic create the deployments, service and pods with
# replicaset

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb

spec:
  selector:
    matchLabels:
      app: mongodb

  template:
    metadata:
      labels:
        app: mongodb

    spec:
      containers:
        - name: mongodb
          image: mongo:4.4.5
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongouser

            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongopwd42

