name: CI-CD

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:

  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v1.9.0

        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build and push docker images.
        uses: docker/build-push-action@v2.4.0

        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            imartynetz/api-produto-bootcamp:latest
            imartynetz/api-produto-bootcamp:v${{github.run_number}}

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v2

      - name: Kubernets context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.CLUSTER_CONFIG}}

      - name: Deploy MongoDB
        uses: Azure/k8s-deploy@v1.3
        with:
          manifests: |
            cluster/mongodb/deployment.yml
            cluster/mongodb/service.yml

      - name: Deploy API
        uses: Azure/k8s-deploy@v1.3
        with:
          manifests: |
            cluster/api/deployment.yml
            cluster/api/service.yml

