name: CI-CD

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:

  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v1.9.0
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build and push docker images.

        uses: docker/build-push-action@v2.4.0

        with:
          context: ./src
          file: ./scr/Dockerfile
          push: true
          tags: |
            imartynetz/api-produto-bootcamp:latest
            imartynetz/api-produto-bootcamp:v${{github.run_number}}
